apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: exam-resource-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-resource-binding
  namespace: exam
subjects:
- kind: ServiceAccount
  name: default
  namespace: exam
roleRef:
  kind: Role
  name: exam-resource-role
  apiGroup: rbac.authorization.k8s.io
